// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAt2O0wSzrzXza_3GR05GQirDd75HX04wQ',
    appId: '1:237814845171:web:beeda4bd3f0f5c6230f186',
    messagingSenderId: '237814845171',
    projectId: 'desafio-fe594',
    authDomain: 'desafio-fe594.firebaseapp.com',
    storageBucket: 'desafio-fe594.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn59E3I_ZxqUXxBVAJZSrj3dUWhcgfuS8',
    appId: '1:237814845171:android:084978ac1d17e75630f186',
    messagingSenderId: '237814845171',
    projectId: 'desafio-fe594',
    storageBucket: 'desafio-fe594.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhmMx_i8CGZuGXCIrkOY4_4_e2z5Em4IE',
    appId: '1:237814845171:ios:a6b38bc11a35542d30f186',
    messagingSenderId: '237814845171',
    projectId: 'desafio-fe594',
    storageBucket: 'desafio-fe594.firebasestorage.app',
    iosBundleId: 'com.example.desafio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhmMx_i8CGZuGXCIrkOY4_4_e2z5Em4IE',
    appId: '1:237814845171:ios:a6b38bc11a35542d30f186',
    messagingSenderId: '237814845171',
    projectId: 'desafio-fe594',
    storageBucket: 'desafio-fe594.firebasestorage.app',
    iosBundleId: 'com.example.desafio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAt2O0wSzrzXza_3GR05GQirDd75HX04wQ',
    appId: '1:237814845171:web:f5dd4f45956c20e730f186',
    messagingSenderId: '237814845171',
    projectId: 'desafio-fe594',
    authDomain: 'desafio-fe594.firebaseapp.com',
    storageBucket: 'desafio-fe594.firebasestorage.app',
  );
}
